version: "3"
networks:
    dbwebb:
services:
    test:
        image: test:latest
        volumes:
            - "./:/home/test/tests"
    db:
        image: mysql/mysql-server:5.7
        container_name: database
        expose:
            - "3306"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD="yes"
            - MYSQL_DATABASE=microblog_db
            - MYSQL_USER=microblog
            - MYSQL_PASSWORD=zxcqweasd123
        networks:
            dbwebb:
        restart:
            "always"
    prod:
        build:
            dockerfile: docker/Dockerfile_prod
            context: .
        container_name: microblog
        ports:
            - "8000:5000"
        expose:
            - "8000"
        environment:
            - SECRET_KEY="my-secret-key"
            - DATABASE_URL=mysql+pymysql://microblog:zxcqweasd123@db:3306/microblog_db
        links:
            - db:database
        restart:
            "always"
        networks:
            dbwebb:
